// Generated by gencpp from file belka-gait-commander/ShouldersGaitCommand.msg
// DO NOT EDIT!


#ifndef BELKA-GAIT-COMMANDER_MESSAGE_SHOULDERSGAITCOMMAND_H
#define BELKA-GAIT-COMMANDER_MESSAGE_SHOULDERSGAITCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace belka-gait-commander
{
template <class ContainerAllocator>
struct ShouldersGaitCommand_
{
  typedef ShouldersGaitCommand_<ContainerAllocator> Type;

  ShouldersGaitCommand_()
    : shoulders_command()  {
    }
  ShouldersGaitCommand_(const ContainerAllocator& _alloc)
    : shoulders_command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shoulders_command_type;
  _shoulders_command_type shoulders_command;





  typedef boost::shared_ptr< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ShouldersGaitCommand_

typedef ::belka-gait-commander::ShouldersGaitCommand_<std::allocator<void> > ShouldersGaitCommand;

typedef boost::shared_ptr< ::belka-gait-commander::ShouldersGaitCommand > ShouldersGaitCommandPtr;
typedef boost::shared_ptr< ::belka-gait-commander::ShouldersGaitCommand const> ShouldersGaitCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace belka-gait-commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'belka-gait-commander': ['/home/drew/repositories/2d-spine-control-hardware/ros-belka/src/belka-gait-commander/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba9308f196c49d06e4333c12eec0f361";
  }

  static const char* value(const ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba9308f196c49d06ULL;
  static const uint64_t static_value2 = 0xe4333c12eec0f361ULL;
};

template<class ContainerAllocator>
struct DataType< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "belka-gait-commander/ShouldersGaitCommand";
  }

  static const char* value(const ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string shoulders_command\n"
;
  }

  static const char* value(const ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shoulders_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShouldersGaitCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::belka-gait-commander::ShouldersGaitCommand_<ContainerAllocator>& v)
  {
    s << indent << "shoulders_command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shoulders_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BELKA-GAIT-COMMANDER_MESSAGE_SHOULDERSGAITCOMMAND_H
